##############################################################################
# Exported wrappers.
#
# GENERATED by tools/build_medpkg.R -- do not edit by hand.
#
# Every signature below is copied verbatim from the corresponding function in
# inst/method/<module>.R, so the public API cannot drift from the method code.
# Each body re-dispatches the matched call into the module's private
# environment, leaving argument matching and defaults to the implementation.
##############################################################################

#' Multilevel mediation analysis under structured unmeasured confounding
#'
#' Wrapper for `macc()` in the `macc` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("macc", "macc")`.
#' @return The value of `macc::macc()`.
#' @export
macc <- function(dat, model.type = c("single", "multilevel", "twolevel"),
                 method = c("HL", "TS", "HL-TS"), delta = NULL, interval = c(-0.9, 0.9),
                 tol = 0.001, max.itr = 500, conf.level = 0.95,
                 optimizer = c("optimx", "bobyqa", "Nelder_Mead"),
                 mix.pkg = c("nlme", "lme4"), random.indep = TRUE, random.var.equal = FALSE,
                 u.int = FALSE, Sigma.update = TRUE, var.constraint = TRUE,
                 random.var.update = TRUE, logLik.type = c("logLik", "HL"),
                 error.indep = TRUE, error.var.equal = FALSE, sens.plot = FALSE,
                 sens.interval = seq(-1, 1, by = 0.01), legend.pos = "topright",
                 xlab = expression(delta), ylab = expression(hat(AB)), cex.lab = 1,
                 cex.axis = 1, lgd.cex = 1, lgd.pt.cex = 1, plot.delta0 = TRUE, ...) {
  .med_call("macc", "macc", match.call(), parent.frame())
}

#' Simulate single-level data for macc()
#'
#' Wrapper for `sim.data.single()` in the `macc` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("macc", "sim.data.single")`.
#' @return The value of `macc::sim.data.single()`.
#' @export
macc_sim_single <- function(Z, Theta, Sigma) {
  .med_call("macc", "sim.data.single", match.call(), parent.frame())
}

#' Simulate multilevel data for macc()
#'
#' Wrapper for `sim.data.multi()` in the `macc` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("macc", "sim.data.multi")`.
#' @return The value of `macc::sim.data.multi()`.
#' @export
macc_sim_multi <- function(Z.list, N, K = 1, Theta, Sigma, Psi = diag(rep(1, 3)),
                           Lambda = diag(rep(1, 3))) {
  .med_call("macc", "sim.data.multi", match.call(), parent.frame())
}

#' Granger mediation analysis of time series
#'
#' Wrapper for `gma()` in the `gma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("gma", "gma")`.
#' @return The value of `gma::gma()`.
#' @export
gma <- function(dat, model.type = c("single", "twolevel"), method = c("HL", "TS", "HL-TS"),
                delta = NULL, p = 1, single.var.asmp = TRUE, sens.plot = FALSE,
                sens.delta = seq(-1, 1, by = 0.01), legend.pos = "topright",
                xlab = expression(delta), ylab = expression(hat(AB)), cex.lab = 1,
                cex.axis = 1, lgd.cex = 1, lgd.pt.cex = 1, plot.delta0 = TRUE,
                interval = c(-0.9, 0.9), tol = 1e-04, max.itr = 500, conf.level = 0.95,
                error.indep = TRUE, error.var.equal = FALSE, Sigma.update = TRUE,
                var.constraint = TRUE, ...) {
  .med_call("gma", "gma", match.call(), parent.frame())
}

#' Simulate a single time series for gma()
#'
#' Wrapper for `sim.data.ts.single()` in the `gma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("gma", "sim.data.ts.single")`.
#' @return The value of `gma::sim.data.ts.single()`.
#' @export
gma_sim_single <- function(n, Z, A, B, C, Sigma, W, Delta = NULL, p = NULL, nburn = 100) {
  .med_call("gma", "sim.data.ts.single", match.call(), parent.frame())
}

#' Simulate two-level time series for gma()
#'
#' Wrapper for `sim.data.ts.two()` in the `gma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("gma", "sim.data.ts.two")`.
#' @return The value of `gma::sim.data.ts.two()`.
#' @export
gma_sim_two <- function(Z.list, N, theta, Sigma, W, Delta = NULL, p = NULL,
                        Lambda = diag(rep(1, 3)), nburn = 100) {
  .med_call("gma", "sim.data.ts.two", match.call(), parent.frame())
}

#' Sparse principal component based high-dimensional mediation analysis
#'
#' Wrapper for `spcma()` in the `spcma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("spcma", "spcma")`.
#' @return The value of `spcma::spcma()`.
#' @export
spcma <- function(X, M, Y, adaptive = FALSE, var.per = 0.8, n.pc = NULL, D = NULL,
                  gamma = 0, eps = 1e-04, maxsteps = 2000, per.jump = 0.7, boot = TRUE,
                  sims = 1000, boot.ci.type = c("bca", "perc"), conf.level = 0.95,
                  p.adj.method = c("BH", "bonferroni", "BY"), PC.run = TRUE) {
  .med_call("spcma", "spcma", match.call(), parent.frame())
}

#' Baron-Kenny style multivariate mediation analysis
#'
#' Wrapper for `mcma_BK()` in the `spcma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("spcma", "mcma_BK")`.
#' @return The value of `spcma::mcma_BK()`.
#' @export
mcma_bk <- function(X, M, Y, sims = 1000, boot = TRUE, boot.ci.type = c("bca", "perc"),
                    conf.level = 0.95, p.adj.method = c("BH", "bonferroni", "BY")) {
  .med_call("spcma", "mcma_BK", match.call(), parent.frame())
}

#' Principal component based mediation analysis
#'
#' Wrapper for `mcma_PCA()` in the `spcma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("spcma", "mcma_PCA")`.
#' @return The value of `spcma::mcma_PCA()`.
#' @export
mcma_pca <- function(X, M, Y, adaptive = FALSE, var.per = 0.8, n.pc = NULL, boot = TRUE,
                     sims = 1000, boot.ci.type = c("bca", "perc"), conf.level = 0.95,
                     p.adj.method = c("BH", "bonferroni", "BY")) {
  .med_call("spcma", "mcma_PCA", match.call(), parent.frame())
}

#' Plot spcma coefficient estimates
#'
#' Wrapper for `plot_spcma()` in the `spcma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("spcma", "plot_spcma")`.
#' @return The value of `spcma::plot_spcma()`.
#' @export
plot_spcma <- function(object, plot.coef = c("alpha", "beta", "IE"), cex.lab = 1,
                       cex.axis = 1, pt.cex = 1, ...) {
  .med_call("spcma", "plot_spcma", match.call(), parent.frame())
}

#' Concurrent functional mediation model
#'
#' Wrapper for `FMA.concurrent()` in the `cfma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("cfma", "FMA.concurrent")`.
#' @return The value of `cfma::FMA.concurrent()`.
#' @export
cfma_concurrent <- function(Z, M, Y, intercept = TRUE, basis = NULL, Ld2.basis = NULL,
                            basis.type = c("fourier"), nbasis = 3, timeinv = c(0, 1),
                            timegrids = NULL, lambda.m = 0.01, lambda.y = 0.01) {
  .med_call("cfma", "FMA.concurrent", match.call(), parent.frame())
}

#' Cross-validation for the concurrent functional mediation model
#'
#' Wrapper for `FMA.concurrent.CV()` in the `cfma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("cfma", "FMA.concurrent.CV")`.
#' @return The value of `cfma::FMA.concurrent.CV()`.
#' @export
cfma_concurrent_cv <- function(Z, M, Y, intercept = TRUE, basis = NULL, Ld2.basis = NULL,
                               basis.type = c("fourier"), nbasis = 3, timeinv = c(0, 1),
                               timegrids = NULL, lambda = NULL, nfolds = 5) {
  .med_call("cfma", "FMA.concurrent.CV", match.call(), parent.frame())
}

#' Bootstrap inference for the concurrent functional mediation model
#'
#' Wrapper for `FMA.concurrent.boot()` in the `cfma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("cfma", "FMA.concurrent.boot")`.
#' @return The value of `cfma::FMA.concurrent.boot()`.
#' @export
cfma_concurrent_boot <- function(Z, M, Y, intercept = TRUE, basis = NULL, Ld2.basis = NULL,
                                 basis.type = c("fourier"), nbasis = 3, timeinv = c(0, 1),
                                 timegrids = NULL, lambda.m = 0.01, lambda.y = 0.01,
                                 sims = 1000, boot = TRUE, boot.ci.type = c("bca", "perc"),
                                 conf.level = 0.95, verbose = TRUE) {
  .med_call("cfma", "FMA.concurrent.boot", match.call(), parent.frame())
}

#' Historical-influence functional mediation model
#'
#' Wrapper for `FMA.historical()` in the `cfma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("cfma", "FMA.historical")`.
#' @return The value of `cfma::FMA.historical()`.
#' @export
cfma_historical <- function(Z, M, Y, delta.grid1 = 1, delta.grid2 = 1, delta.grid3 = 1,
                            intercept = TRUE, basis1 = NULL, Ld2.basis1 = NULL,
                            basis2 = NULL, Ld2.basis2 = NULL, basis.type = c("fourier"),
                            nbasis1 = 3, nbasis2 = 3, timeinv = c(0, 1), timegrids = NULL,
                            lambda1.m = 0.01, lambda2.m = 0.01, lambda1.y = 0.01,
                            lambda2.y = 0.01) {
  .med_call("cfma", "FMA.historical", match.call(), parent.frame())
}

#' Cross-validation for the historical-influence functional mediation model
#'
#' Wrapper for `FMA.historical.CV()` in the `cfma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("cfma", "FMA.historical.CV")`.
#' @return The value of `cfma::FMA.historical.CV()`.
#' @export
cfma_historical_cv <- function(Z, M, Y, delta.grid1 = 1, delta.grid2 = 1, delta.grid3 = 1,
                               intercept = TRUE, basis1 = NULL, Ld2.basis1 = NULL,
                               basis2 = NULL, Ld2.basis2 = NULL, basis.type = c("fourier"),
                               nbasis1 = 3, nbasis2 = 3, timeinv = c(0, 1),
                               timegrids = NULL, lambda1 = NULL, lambda2 = NULL, nfolds = 5) {
  .med_call("cfma", "FMA.historical.CV", match.call(), parent.frame())
}

#' Bootstrap inference for the historical-influence functional mediation model
#'
#' Wrapper for `FMA.historical.boot()` in the `cfma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("cfma", "FMA.historical.boot")`.
#' @return The value of `cfma::FMA.historical.boot()`.
#' @export
cfma_historical_boot <- function(Z, M, Y, delta.grid1 = 1, delta.grid2 = 1, delta.grid3 = 1,
                                 intercept = TRUE, basis1 = NULL, Ld2.basis1 = NULL,
                                 basis2 = NULL, Ld2.basis2 = NULL,
                                 basis.type = c("fourier"), nbasis1 = 3, nbasis2 = 3,
                                 timeinv = c(0, 1), timegrids = NULL, lambda1.m = 0.01,
                                 lambda2.m = 0.01, lambda1.y = 0.01, lambda2.y = 0.01,
                                 sims = 1000, boot = TRUE, boot.ci.type = c("bca", "perc"),
                                 conf.level = 0.95, verbose = TRUE) {
  .med_call("cfma", "FMA.historical.boot", match.call(), parent.frame())
}

#' Pathway Lasso estimation and selection with high-dimensional mediators
#'
#' Wrapper for `pathlasso()` in the `pathwaylasso` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("pathwaylasso", "pathlasso")`.
#' @return The value of `pathwaylasso::pathlasso()`.
#' @export
pathlasso <- function(X, M, Y, lambda = 1, omega = 0, phi = 1, Phi1 = NULL, Phi2 = NULL,
                      rho = 1, rho.increase = FALSE, standardize = TRUE, tol = 1e-10,
                      max.itr = 10000, thred = 1e-10, est_thred = FALSE, Sigma1 = NULL,
                      Sigma2 = NULL, trace = FALSE, Theta0 = NULL, D0 = NULL, alpha0 = NULL,
                      beta0 = NULL) {
  .med_call("pathwaylasso", "pathlasso", match.call(), parent.frame())
}

#' Pathway Lasso tuning by Kappa selection criterion
#'
#' Wrapper for `mediation_net_ADMM_NC_KSC()` in the `pathwaylasso` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("pathwaylasso", "mediation_net_ADMM_NC_KSC")`.
#' @return The value of `pathwaylasso::mediation_net_ADMM_NC_KSC()`.
#' @export
pathlasso_ksc <- function(Z, M, R, zero.cutoff = 0.001, n.rep = 5, vss.cut = 0.1,
                          lambda = 10^c(seq(-3, 1, length.out = 31)[-1], seq(1, 5, length.out = 11)[-1]),
                          omega = 0, phi = 1, Phi1 = NULL, Phi2 = NULL, rho = 1,
                          rho.increase = FALSE, tol = 1e-10, max.itr = 10000, thred = 1e-10,
                          Sigma1 = NULL, Sigma2 = NULL, trace = FALSE, Theta0 = NULL,
                          D0 = NULL, alpha0 = NULL, beta0 = NULL) {
  .med_call("pathwaylasso", "mediation_net_ADMM_NC_KSC", match.call(), parent.frame())
}

#' Variable selection stability for a single Pathway Lasso split
#'
#' Wrapper for `mediation_net_ADMM_NC_VSS()` in the `pathwaylasso` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("pathwaylasso", "mediation_net_ADMM_NC_VSS")`.
#' @return The value of `pathwaylasso::mediation_net_ADMM_NC_VSS()`.
#' @export
pathlasso_vss <- function(data1, data2, zero.cutoff = 0.001, lambda = 1, omega = 0, phi = 1,
                          data1_Phi1 = NULL, data1_Phi2 = NULL, data2_Phi1 = NULL,
                          data2_Phi2 = NULL, rho = 1, rho.increase = FALSE, tol = 1e-10,
                          max.itr = 10000, thred = 1e-10, Sigma1 = NULL, Sigma2 = NULL,
                          trace = FALSE, Theta0 = NULL, D0 = NULL, alpha0 = NULL,
                          beta0 = NULL) {
  .med_call("pathwaylasso", "mediation_net_ADMM_NC_VSS", match.call(), parent.frame())
}

#' Variable selection stability over a Pathway Lasso tuning path
#'
#' Wrapper for `mediation_net_ADMM_NC_VSS_rep()` in the `pathwaylasso` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("pathwaylasso", "mediation_net_ADMM_NC_VSS_rep")`.
#' @return The value of `pathwaylasso::mediation_net_ADMM_NC_VSS_rep()`.
#' @export
pathlasso_vss_rep <- function(data1, data2, zero.cutoff = 0.001,
                              lambda = 10^c(seq(-3, 1, length.out = 31)[-1], seq(1, 5, length.out = 11)[-1]),
                              omega = 0, phi = 1, data1_Phi1 = NULL, data1_Phi2 = NULL,
                              data2_Phi1 = NULL, data2_Phi2 = NULL, rho = 1,
                              rho.increase = FALSE, tol = 1e-10, max.itr = 10000,
                              thred = 1e-10, Sigma1 = NULL, Sigma2 = NULL, trace = FALSE,
                              Theta0 = NULL, D0 = NULL, alpha0 = NULL, beta0 = NULL) {
  .med_call("pathwaylasso", "mediation_net_ADMM_NC_VSS_rep", match.call(), parent.frame())
}

#' Simulate correlated-error data for pathlasso()
#'
#' Wrapper for `sim.data_dep()` in the `pathwaylasso` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("pathwaylasso", "sim.data_dep")`.
#' @return The value of `pathwaylasso::sim.data_dep()`.
#' @export
pathlasso_sim <- function(n, Z, a, b, c, Delta, Xi1, Sigma2) {
  .med_call("pathwaylasso", "sim.data_dep", match.call(), parent.frame())
}

#' Multimodal pathway analysis with two blocks of high-dimensional mediators
#'
#' Wrapper for `pathlasso.2b()` in the `multimodal` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("multimodal", "pathlasso.2b")`.
#' @return The value of `multimodal::pathlasso.2b()`.
#' @export
pathlasso2b <- function(X, M1, M2, Y, kappa1, kappa2, kappa3, kappa4, nu1 = 1, nu2 = 1,
                        mu1 = 0, mu2 = 0, rho = 1, standardize = TRUE, max.itr = 10000,
                        tol = 1e-06, rho.increase = FALSE, trace = FALSE, beta0 = NULL,
                        theta0 = NULL, zeta0 = NULL, pi0 = NULL, Lambda0 = NULL) {
  .med_call("multimodal", "pathlasso.2b", match.call(), parent.frame())
}

#' Mediation analysis with high-dimensional exposures and mediators
#'
#' Wrapper for `HDCauseMediation()` in the `hdexposure` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("hdexposure", "HDCauseMediation")`.
#' @return The value of `hdexposure::HDCauseMediation()`.
#' @export
hdmediation <- function(X, M, Y, lambda = 0, pi = 1, phi = 2, delta = 0.1, rho = 1,
                        standardize = TRUE, max.itr = 10000, tol = 1e-06,
                        rho.increase = FALSE, trace = FALSE, alpha0 = NULL, beta0 = NULL,
                        gamma0 = NULL) {
  .med_call("hdexposure", "HDCauseMediation", match.call(), parent.frame())
}

#' Principal-component variant of hdmediation()
#'
#' Wrapper for `HDCauseMediationPCA()` in the `hdexposure` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("hdexposure", "HDCauseMediationPCA")`.
#' @return The value of `hdexposure::HDCauseMediationPCA()`.
#' @export
hdmediation_pca <- function(X, M, Y, adaptive = FALSE, var.prop = 0.9, n.pc = NULL,
                            lambda = 0, pi = 1, phi = 2, delta = 0.1, rho = 1,
                            standardize = TRUE, max.itr = 10000, tol = 1e-06,
                            rho.increase = FALSE, trace = FALSE, alpha0 = NULL,
                            beta0 = NULL, gamma0 = NULL) {
  .med_call("hdexposure", "HDCauseMediationPCA", match.call(), parent.frame())
}

#' Principal component mediation analysis for multiple exposures and mediators
#'
#' Wrapper for `HDEM.loglike.opt()` in the `pcma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("pcma", "HDEM.loglike.opt")`.
#' @return The value of `pcma::HDEM.loglike.opt()`.
#' @export
pcma <- function(X, M, Y, stop.crt = c("nD", "IE"), nD = NULL, conf.level = 0.95,
                 boot = TRUE, sims = 1000, boot.ci.type = c("perc", "SE"), max.itr = 1000,
                 tol = 1e-04, trace = FALSE, phi0.mat = NULL, psi0.mat = NULL,
                 ninitial = NULL, seed = 100, verbose = TRUE) {
  .med_call("pcma", "HDEM.loglike.opt", match.call(), parent.frame())
}

#' Bootstrap inference for pcma()
#'
#' Wrapper for `HDEM.inf()` in the `pcma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("pcma", "HDEM.inf")`.
#' @return The value of `pcma::HDEM.inf()`.
#' @export
pcma_inf <- function(X, M, Y, phi, psi, boot = TRUE, sims = 1000,
                     boot.ci.type = c("perc", "SE"), conf.level = 0.95, verbose = TRUE) {
  .med_call("pcma", "HDEM.inf", match.call(), parent.frame())
}

#' Asymptotic inference for pcma()
#'
#' Wrapper for `HDEM.inf.asmp()` in the `pcma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("pcma", "HDEM.inf.asmp")`.
#' @return The value of `pcma::HDEM.inf.asmp()`.
#' @export
pcma_inf_asmp <- function(X, M, Y, phi, psi, conf.level = 0.95) {
  .med_call("pcma", "HDEM.inf.asmp", match.call(), parent.frame())
}

#' Effect estimates at fixed pcma() projections
#'
#' Wrapper for `HDEM.coef()` in the `pcma` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("pcma", "HDEM.coef")`.
#' @return The value of `pcma::HDEM.coef()`.
#' @export
pcma_coef <- function(X, M, Y, phi, psi) {
  .med_call("pcma", "HDEM.coef", match.call(), parent.frame())
}

#' Mediation analysis with a graph (covariance matrix) mediator
#'
#' Wrapper for `CAPMediation()` in the `gmed` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("gmed", "CAPMediation")`.
#' @return The value of `gmed::CAPMediation()`.
#' @export
gmed <- function(X, M, Y, H = NULL, stop.crt = c("nD", "DfD"), nD = NULL, DfD.thred = 2,
                 Y.remove = TRUE, max.itr = 1000, tol = 1e-04, trace = FALSE,
                 score.return = TRUE, theta0.mat = NULL, ninitial = NULL, seed = 100,
                 verbose = TRUE) {
  .med_call("gmed", "CAPMediation", match.call(), parent.frame())
}

#' Bootstrap inference for gmed()
#'
#' Wrapper for `CAPMediation_boot()` in the `gmed` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("gmed", "CAPMediation_boot")`.
#' @return The value of `gmed::CAPMediation_boot()`.
#' @export
gmed_boot <- function(X, M, Y, theta = NULL, H = NULL, boot = TRUE, sims = 1000,
                      boot.ci.type = c("se", "perc"), conf.level = 0.95, seed.boot = 100,
                      verbose = TRUE) {
  .med_call("gmed", "CAPMediation_boot", match.call(), parent.frame())
}

#' Refit gmed() effects at fixed projections
#'
#' Wrapper for `CAPMediation_refit()` in the `gmed` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("gmed", "CAPMediation_refit")`.
#' @return The value of `gmed::CAPMediation_refit()`.
#' @export
gmed_refit <- function(X, M, Y, Theta) {
  .med_call("gmed", "CAPMediation_refit", match.call(), parent.frame())
}

#' Bootstrap inference for gmed_refit()
#'
#' Wrapper for `CAPMediation_refit_boot()` in the `gmed` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("gmed", "CAPMediation_refit_boot")`.
#' @return The value of `gmed::CAPMediation_refit_boot()`.
#' @export
gmed_refit_boot <- function(X, M, Y, Theta = NULL, H = NULL, boot = TRUE, sims = 1000,
                            boot.ci.type = c("se", "perc"), conf.level = 0.95,
                            seed.boot = 100, verbose = TRUE) {
  .med_call("gmed", "CAPMediation_refit_boot", match.call(), parent.frame())
}

#' Effect estimates at a fixed gmed() projection
#'
#' Wrapper for `CAPMediation_coef()` in the `gmed` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("gmed", "CAPMediation_coef")`.
#' @return The value of `gmed::CAPMediation_coef()`.
#' @export
gmed_coef <- function(X, M, Y, theta) {
  .med_call("gmed", "CAPMediation_coef", match.call(), parent.frame())
}

#' Heterogeneous (moderated) causal mediation effect estimation
#'
#' Wrapper for `med.inter()` in the `heteromed` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("heteromed", "med.inter")`.
#' @return The value of `heteromed::med.inter()`.
#' @export
hetermed <- function(X, M, Y, Z, method = c("OLS", "genlasso"),
                     genlasso.tune.method = c("Cp", "BIC", "GCV")) {
  .med_call("heteromed", "med.inter", match.call(), parent.frame())
}

#' Inference for hetermed()
#'
#' Wrapper for `med.inter.inf()` in the `heteromed` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("heteromed", "med.inter.inf")`.
#' @return The value of `heteromed::med.inter.inf()`.
#' @export
hetermed_inf <- function(X, M, Y, Z, out.med.inter, conf.level = 0.95,
                         method = c("OLS", "genlasso"),
                         genlasso.tune.method = c("Cp", "BIC", "GCV"), B = 500,
                         zero.thred = 1e-04, lambda.ridge = 0.001, verbose = TRUE) {
  .med_call("heteromed", "med.inter.inf", match.call(), parent.frame())
}

#' Individual treatment/mediation effects from hetermed() parameters
#'
#' Wrapper for `med.inter.ITE()` in the `heteromed` method module.
#'
#' @param ... Passed to the implementation; see `med_internal("heteromed", "med.inter.ITE")`.
#' @return The value of `heteromed::med.inter.ITE()`.
#' @export
hetermed_ite <- function(X, Z, alpha0, alpha1, beta0, beta1, gamma0, gamma1) {
  .med_call("heteromed", "med.inter.ITE", match.call(), parent.frame())
}

